# Generated by Django 4.1.3 on 2022-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
